### PR TITLE
Print tasks errors

### PR DESCRIPTION
**Pull request by martinRenou**

### CODE REVIEW

**Comment by martinRenou** [comment]
@osrjv As we discussed, I am printing the lib import issues and tasks errors. The ugly workaround has been removed in latest release.

**Comment by osrjv** [comment]
Are `print()` calls from here visible in notebooks?

What I think is still lacking is that the cell execution status is ok even if tasks fail. Previously the semantics were that, for instance, "Run all cells" would stop in the first cell where tasks/keywords failed. If I'm looking at xeus-robot code correctly (https://github.com/jupyter-xeus/xeus-robot/blob/master/src/xinterpreter.cpp#L210), an exception would have to be thrown for the cell to return an error state.

You could do something like check if `result.statistics.total.failed` is non-zero and throw those messages inside an exception instead of printing. However, it looks like then the log button/widget wouldn't appear. Would it be feasible to check those failure counts on xeus-robot side and return the state accordingly but also give the log?

Here's a screenshot of the old kernel where a failed task prompted an error with traceback and the log button:
image

**Comment by martinRenou** [comment]
> Are print() calls from here visible in notebooks?

Yes they are visible

> What I think is still lacking is that the cell execution status is ok even if tasks fail. Previously the semantics were that, for instance, "Run all cells" would stop in the first cell where tasks/keywords failed. If I'm looking at xeus-robot code correctly (https://github.com/jupyter-xeus/xeus-robot/blob/master/src/xinterpreter.cpp#L210), an exception would have to be thrown for the cell to return an error state.

Ok 👍🏽 So let's raise an exception then. This would make xeus-robot consider it as an execution failure.

**Comment by osrjv** [comment]
But we'd be left without the log widget, right? Since it does an early return on errors. I'm not sure if this is fixable without some small change to xeus-robot side.

**Comment by martinRenou** [comment]
Indeed. We'll need to change the logic between robotframework-interpreter and xeus-robot then

**Pull request merged**
